packages:
  - "packages/*"
  - "services/*"
  - "apps/desktop-edge-sync"
  - "apps/mobile-grossiste-b"
  - "apps/mobile-detaillant"
  - "apps/web-grossiste-a"
  - "apps/web-industrial-nextjs"
  - "apps/mobile-terrain-shell"
