/** Clés événements canoniques — BACKOFFICE-01-D (parcours métier). */
export const OPERATIONAL_JOURNEY_EVENTS = {
  AUTH: {
    LOGIN_START: "login_start",
    LOGIN_SUCCESS: "login_success",
    LOGIN_FAILURE: "login_failure",
    OTP_REQUEST: "otp_request",
    OTP_SUCCESS: "otp_success",
    OTP_FAILURE: "otp_failure",
    RESET_PASSWORD_START: "reset_password_start",
    RESET_PASSWORD_SUCCESS: "reset_password_success",
    ENTERPRISE_INVITATION_START: "enterprise_invitation_start",
    ENTERPRISE_INVITATION_COMPLETE: "enterprise_invitation_completed",
  },
  CATALOG: {
    PRODUCT_CREATE_START: "product_create_started",
    PRODUCT_FORM_OPEN: "product_form_open",
    PRODUCT_DRAFT_SAVED: "product_draft_saved",
    PRODUCT_IMAGE_UPLOAD: "product_image_upload",
    PRODUCT_PUBLISH: "product_create_completed",
    PRODUCT_EDIT: "product_edit_started",
    PRODUCT_EDIT_COMPLETE: "product_edit_completed",
  },
  ORDER: {
    CREATE_START: "order_create_started",
    CREATE_COMPLETE: "order_create_completed",
    VALIDATE: "order_validated",
    REFUSE: "order_refused",
    CANCEL: "order_cancelled",
  },
  WALLET: {
    ACTIVATION_START: "wallet_activation_started",
    ACTIVATION_COMPLETE: "wallet_activation_completed",
    PAYMENT: "wallet_payment",
    PAYMENT_FAILED: "wallet_payment_failed",
    WITHDRAW: "wallet_withdraw",
    TOPUP: "wallet_topup",
  },
  MESSAGING: {
    CONVERSATION_OPEN: "conversation_open",
    MESSAGE_SEND: "message_sent",
    NEGOTIATION: "negotiation_started",
    COMMERCIAL_PROPOSAL: "commercial_proposal_sent",
  },
  NETWORK: {
    PARTNER_INVITE: "relationship_invitation_sent",
    RELATION_VALIDATE: "relationship_accept_completed",
    RELATION_REJECT: "relationship_reject_completed",
  },
  INDUSTRIAL: {
    POLE_DASHBOARD: "pole_dashboard_view",
    SIGNAL_READ: "industrial_signal_read",
    ANALYTICS_VIEW: "industrial_analytics_view",
    REPORT_EXPORT: "industrial_report_export",
  },
  BACKOFFICE: {
    OPERATOR_LOGIN: "backoffice_login_success",
    TICKET_OPEN: "support_ticket_open",
    GOVERNANCE_ACTION: "governance_action",
    FEATURE_FLAG_CHANGE: "feature_flag_change",
  },
} as const;

export const CRITICAL_OBSERVABILITY_SCREENS = [
  "auth.login",
  "auth.otp",
  "auth.reset_password",
  "catalog.product_form",
  "catalog.product_publish",
  "order.create",
  "order.validate",
  "wallet.activation",
  "wallet.payment",
  "messaging.conversation",
  "network.partner_invite",
  "industrial.dashboard",
  "backoffice.login",
  "backoffice.ticket",
] as const;
