import type { PoleSlug } from "./types";

export type PoleRegistryEntry = {
  slug: PoleSlug;
  /** Uppercase enum style for websocket subscribe */
  poleChannel: string;
  title: string;
  subtitle: string;
  /** Accent for kinetic header (not SaaS card chrome). */
  accent: "amber" | "cyan" | "violet" | "rose" | "emerald" | "slate";
  mapEmphasis: "heatmap" | "movement" | "pressure" | "incident" | "network";
  /** MapControlEngine command vocabulary (Instruction 5 §4). */
  mapCommandFamilies: string[];
};

export const POLE_REGISTRY: PoleRegistryEntry[] = [
  {
    slug: "direction-strategy",
    poleChannel: "DIRECTION_STRATEGY",
    title: "Direction & strategy",
    subtitle: "Macro corridor theatre — demand ridges & expansion vectors",
    accent: "amber",
    mapEmphasis: "heatmap",
    mapCommandFamilies: [
      "national_demand_heatmap",
      "commercial_growth_zones",
      "strategic_tension_zones",
      "partner_expansion_density",
      "macro_consumption_evolution",
    ],
  },
  {
    slug: "commercial-network",
    poleChannel: "COMMERCIAL_NETWORK",
    title: "Commercial network",
    subtitle: "Relationship-field density — voids, health, growth opportunities",
    accent: "cyan",
    mapEmphasis: "network",
    mapCommandFamilies: [
      "active_wholesalers",
      "retailer_relationship_density",
      "inactive_zones",
      "network_growth_opportunities",
      "relationship_health",
    ],
  },
  {
    slug: "marketing-activation",
    poleChannel: "MARKETING_ACTIVATION",
    title: "Marketing activation",
    subtitle: "Diffusion geometry — attention gravity & seasonal shifts",
    accent: "violet",
    mapEmphasis: "heatmap",
    mapCommandFamilies: [
      "campaign_diffusion",
      "sponsored_product_propagation",
      "engagement_zones",
      "product_attention_signals",
      "seasonal_behavioral_shifts",
    ],
  },
  {
    slug: "orders-adv",
    poleChannel: "ORDERS_ADV",
    title: "Orders & ADV",
    subtitle: "Transactional commerce intelligence — negotiations, reservations, conversational execution",
    accent: "rose",
    mapEmphasis: "movement",
    mapCommandFamilies: [
      "order_flow_density",
      "pending_orders",
      "blocked_orders",
      "negotiation_activity",
      "fulfillment_bottlenecks",
    ],
  },
  {
    slug: "supply-logistics",
    poleChannel: "SUPPLY_LOGISTICS",
    title: "Supply & logistics",
    subtitle: "Movement intelligence — dwell, rupture, ETA risk, anomalies",
    accent: "emerald",
    mapEmphasis: "movement",
    mapCommandFamilies: [
      "truck_movement",
      "warehouse_activity",
      "route_anomalies",
      "stock_movement",
      "delivery_eta_risk",
    ],
  },
  {
    slug: "finance-collections",
    poleChannel: "FINANCE_COLLECTIONS",
    title: "Finance & collections",
    subtitle: "Liquidity pressure field — velocity, unpaid mass, cadence",
    accent: "amber",
    mapEmphasis: "pressure",
    mapCommandFamilies: [
      "unpaid_zones",
      "payment_velocity",
      "collection_pressure",
      "wallet_activity",
      "delayed_payments",
    ],
  },
  {
    slug: "data-intelligence",
    poleChannel: "DATA_INTELLIGENCE",
    title: "Data intelligence",
    subtitle: "Correlation theatre — anomalies, overlays, forecast cones",
    accent: "slate",
    mapEmphasis: "heatmap",
    mapCommandFamilies: [
      "signal_correlations",
      "predictive_consumption",
      "anomaly_detection",
      "external_data_influence",
      "forecast_projections",
    ],
  },
  {
    slug: "economic-memory",
    poleChannel: "ECONOMIC_MEMORY",
    title: "Economic memory",
    subtitle: "Industrial temporal intelligence — recurrence, crisis signatures, propagation history",
    accent: "slate",
    mapEmphasis: "heatmap",
    mapCommandFamilies: [
      "historical_propagation_density",
      "crisis_signature_corridor",
      "territory_memory_capsules",
      "recurrence_pattern_field",
      "temporal_volatility_envelope",
    ],
  },
  {
    slug: "economic-scenarios",
    poleChannel: "ECONOMIC_SCENARIOS",
    title: "Economic scenarios",
    subtitle: "Industrial futures lattice — trajectories, risk contrast, stabilization levers (symbolic)",
    accent: "violet",
    mapEmphasis: "pressure",
    mapCommandFamilies: [
      "scenario_trajectory_corridor",
      "multi_pole_stress_cone",
      "stabilization_direction_field",
      "scenario_comparison_ridge",
      "prospective_fragility_capsule",
    ],
  },
  {
    slug: "economic-propagation",
    poleChannel: "ECONOMIC_PROPAGATION",
    title: "Economic propagation",
    subtitle: "Nervous-system lattice — shocks, chains, territory fragility, counterfactual simulation",
    accent: "violet",
    mapEmphasis: "pressure",
    mapCommandFamilies: [
      "shock_origin_trace",
      "impact_spread_vectors",
      "fragile_territory_capsules",
      "propagation_chain_geometry",
      "systemic_risk_envelope",
    ],
  },
  {
    slug: "economic-coordination",
    poleChannel: "ECONOMIC_COORDINATION",
    title: "Economic coordination",
    subtitle: "Salle de cohérence transverse — posture système, arbitrages, priorités multi-pôles (symbolique)",
    accent: "cyan",
    mapEmphasis: "pressure",
    mapCommandFamilies: [
      "coordination_posture_field",
      "cross_pole_arbitration_matrix",
      "priority_ladder_geometry",
      "escalation_envelope_trace",
      "conflict_deconfliction_corridor",
    ],
  },
  {
    slug: "economic-command",
    poleChannel: "ECONOMIC_COMMAND",
    title: "Economic command",
    subtitle: "Salle de pilotage exécutif — pressions, arbitrages analytiques, stress proxy, lecture transverse (symbolique)",
    accent: "amber",
    mapEmphasis: "pressure",
    mapCommandFamilies: [
      "executive_pressure_field",
      "silent_tension_trace",
      "pole_arbitration_corridor",
      "systemic_stress_proxy_capsule",
      "advisory_risk_envelope",
    ],
  },
  {
    slug: "industrial-situation-room",
    poleChannel: "INDUSTRIAL_SITUATION_ROOM",
    title: "Industrial situation room",
    subtitle: "Salle de situation industrielle — cellules symboliques, missions stabilisation, dépendances critiques (consultatif)",
    accent: "cyan",
    mapEmphasis: "incident",
    mapCommandFamilies: [
      "situation_cell_corridor",
      "stabilization_mission_trace",
      "critical_dependency_bridge",
      "executive_attention_field",
      "cross_pole_saturation_capsule",
    ],
  },
  {
    slug: "industrial-operational-continuity",
    poleChannel: "INDUSTRIAL_OPERATIONAL_CONTINUITY",
    title: "Industrial operational continuity",
    subtitle: "Couche stabilité / cadence — pressions continuité, corridors critiques, surcharge symbolique (18.7)",
    accent: "emerald",
    mapEmphasis: "pressure",
    mapCommandFamilies: [
      "stability_state_density_field",
      "continuity_pressure_envelope",
      "critical_corridor_trace",
      "cadence_instability_ridge",
      "saturation_proxy_capsule",
    ],
  },
  {
    slug: "industrial-evidence",
    poleChannel: "INDUSTRIAL_EVIDENCE",
    title: "Industrial evidence",
    subtitle: "Couche provenance / confiance — registre consultatif, traces dérivées non causales, limitations explicites (18.8)",
    accent: "slate",
    mapEmphasis: "pressure",
    mapCommandFamilies: [
      "provenance_row_density",
      "trust_matrix_scope_field",
      "derived_trace_corridor",
      "source_map_composition",
      "limitation_disclosure_capsule",
    ],
  },
  {
    slug: "commercial-relationship-graph",
    poleChannel: "COMMERCIAL_RELATIONSHIP_GRAPH",
    title: "Commercial relationship graph",
    subtitle: "Graphe relationnel validé — distribution, dépendances, couverture symbolique (19.1) — pas réseau social",
    accent: "cyan",
    mapEmphasis: "network",
    mapCommandFamilies: [
      "validated_partner_corridor",
      "distribution_dependency_field",
      "commercial_bridge_density",
      "coverage_gap_trace",
      "relationship_stability_capsule",
    ],
  },
  {
    slug: "relational-catalog",
    poleChannel: "RELATIONAL_CATALOG",
    title: "Relational catalog",
    subtitle:
      "Catalogues commerciaux cloisonnés — visibilité relationnelle, sponsor contrôlé, intelligence symbolique (19.2) — pas marketplace ouverte",
    accent: "emerald",
    mapEmphasis: "network",
    mapCommandFamilies: [
      "relationship_visibility_corridor",
      "catalog_density_trace",
      "sponsor_injection_capsule",
      "distribution_gap_lane",
      "validated_partner_scope_field",
    ],
  },
  {
    slug: "relational-cart",
    poleChannel: "RELATIONAL_CART",
    title: "Relational cart",
    subtitle:
      "Préparation de commande relationnelle — revue partenaire, validation corridor, conversion contrôlée (20.5 / 20.6A) — pas checkout public ni paiement",
    accent: "emerald",
    mapEmphasis: "network",
    mapCommandFamilies: [
      "corridor_cart_preparation_lane",
      "partner_review_trace",
      "relational_line_validation_capsule",
      "governance_alignment_read",
      "private_pre_order_file",
    ],
  },
  {
    slug: "relational-orders",
    poleChannel: "RELATIONAL_ORDERS",
    title: "Relational orders",
    subtitle:
      "Commandes corridor privées — orchestration relationnelle, fulfillment symbolique, signaux consultatifs (20.0) — pas checkout public ni paiement intégré",
    accent: "cyan",
    mapEmphasis: "movement",
    mapCommandFamilies: [
      "corridor_order_lane",
      "relationship_scoped_dispatch_read",
      "symbolic_fulfillment_capsule",
      "negotiation_reservation_bridge",
      "wholesale_retail_corridor_file",
    ],
  },
  {
    slug: "relational-predictive-risk",
    poleChannel: "RELATIONAL_ORDERS",
    title: "Risque prédictif opérationnel",
    subtitle:
      "Drift déterministe, collapse SLA, signaux fragilité corridor (20.13) — pas LLM ni notation publique",
    accent: "cyan",
    mapEmphasis: "movement",
    mapCommandFamilies: [
      "predictive_risk_lane",
      "operational_drift_trace",
      "sla_collapse_watch",
      "corridor_fragility_capsule",
      "degradation_pattern_audit",
    ],
  },
  {
    slug: "relational-operational-recommendation",
    poleChannel: "RELATIONAL_ORDERS",
    title: "Recommandations opérationnelles",
    subtitle:
      "Actions corridor déterministes SLA, incidents, gouvernance (20.14) — pas assistant IA ni scoring public",
    accent: "cyan",
    mapEmphasis: "movement",
    mapCommandFamilies: [
      "operational_recommendation_lane",
      "sla_action_trace",
      "incident_escalation_capsule",
      "governance_stabilization_read",
      "collapse_prevention_audit",
    ],
  },
  {
    slug: "relational-operational-orchestration",
    poleChannel: "RELATIONAL_ORDERS",
    title: "Orchestration opérationnelle",
    subtitle:
      "Plans d'action séquencés, stabilisation corridor (20.15) — pas autopilot ni agent autonome",
    accent: "cyan",
    mapEmphasis: "movement",
    mapCommandFamilies: [
      "orchestration_command_lane",
      "stabilization_sequence_trace",
      "human_validation_capsule",
      "corridor_recovery_plan",
      "operational_supervision_audit",
    ],
  },
  {
    slug: "relational-operational-simulation",
    poleChannel: "RELATIONAL_ORDERS",
    title: "Simulation opérationnelle",
    subtitle:
      "Stress tests et projections corridor (20.16) — analytique déterministe, aucune mutation réelle",
    accent: "cyan",
    mapEmphasis: "movement",
    mapCommandFamilies: [
      "simulation_stress_lane",
      "corridor_projection_trace",
      "collapse_propagation_capsule",
      "resilience_analytics_read",
      "operational_what_if_audit",
    ],
  },
  {
    slug: "relational-scenario-review",
    poleChannel: "RELATIONAL_ORDERS",
    title: "Revue scénario & décision",
    subtitle:
      "Comité opérationnel corridor (20.17) — validation humaine traçable, pas autopilot ni assistant IA",
    accent: "violet",
    mapEmphasis: "movement",
    mapCommandFamilies: [
      "scenario_review_lane",
      "human_decision_trace",
      "executive_validation_capsule",
      "dual_validation_audit",
      "corridor_decision_board",
    ],
  },
  {
    slug: "relational-strategic-memory",
    poleChannel: "RELATIONAL_ORDERS",
    title: "Mémoire stratégique",
    subtitle:
      "Registre d'apprentissage corridor explicable (20.18) — capitalisation patterns, pas ML opaque",
    accent: "emerald",
    mapEmphasis: "movement",
    mapCommandFamilies: [
      "strategic_memory_lane",
      "operational_pattern_trace",
      "corridor_learning_capsule",
      "reuse_efficiency_audit",
      "historical_intelligence_read",
    ],
  },
  {
    slug: "relational-economic-signal-graph",
    poleChannel: "RELATIONAL_ORDERS",
    title: "Signaux économiques",
    subtitle:
      "Graphe signaux relationnels (20.19) — corrélation inter-corridors, propagation, clusters — pas wallet ni tracking",
    accent: "amber",
    mapEmphasis: "movement",
    mapCommandFamilies: [
      "economic_signal_lane",
      "cross_corridor_correlation",
      "propagation_risk_capsule",
      "operational_cluster_trace",
      "systemic_exposure_read",
    ],
  },
  {
    slug: "relational-economic-command-center",
    poleChannel: "RELATIONAL_ORDERS",
    title: "Centre de commandement économique",
    subtitle:
      "Supervision stratégique corridor-first (20.20) — signaux critiques, agrégats déterministes — pas tableau ecommerce ni cockpit IA",
    accent: "violet",
    mapEmphasis: "movement",
    mapCommandFamilies: [
      "economic_command_lane",
      "systemic_pressure_trace",
      "corridor_criticality_capsule",
      "multi_signal_supervision_audit",
      "strategic_pressure_read",
    ],
  },
  {
    slug: "relational-economic-pressure",
    poleChannel: "RELATIONAL_ORDERS",
    title: "Pression & dépendances corridor",
    subtitle:
      "Cartographie économique inter-corridors (20.21) — contagion bornée, dépendances asymétriques — pas ERP logistique",
    accent: "amber",
    mapEmphasis: "movement",
    mapCommandFamilies: [
      "economic_pressure_lane",
      "dependency_exposure_trace",
      "contagion_projection_capsule",
      "fragility_zone_audit",
      "saturation_pressure_read",
    ],
  },
  {
    slug: "relational-geo-economic",
    poleChannel: "RELATIONAL_ORDERS",
    title: "Intelligence géo-économique territoriale",
    subtitle:
      "Lecture analytique des bassins et corridors (20.22) — densité opérationnelle, propagation systémique — pas carte logistique ni GPS.",
    accent: "amber",
    mapEmphasis: "movement",
    mapCommandFamilies: [
      "territorial_density_lane",
      "regional_pressure_trace",
      "geo_economic_propagation_capsule",
      "expansion_projection_audit",
      "critical_territory_read",
    ],
  },
  {
    slug: "relational-sector-intelligence",
    poleChannel: "RELATIONAL_ORDERS",
    title: "Intelligence sectorielle & structure de marché",
    subtitle:
      "Couche 20.23 — concentrations sectorielles, propagation inter-industrielle, fragilité marché — pas ERP, pas scoring marketplace.",
    accent: "amber",
    mapEmphasis: "movement",
    mapCommandFamilies: [
      "sector_structure_lane",
      "value_chain_pressure_trace",
      "corridor_sector_propagation_capsule",
      "market_concentration_audit",
      "territorial_sector_balance_read",
    ],
  },
  {
    slug: "relational-macro-economic",
    poleChannel: "RELATIONAL_ORDERS",
    title: "Résilience macro-économique relationnelle",
    subtitle:
      "Couche 20.25 — vulnérabilités systémiques, résilience corridor, propagation adaptive — pas ERP, pas notation publique, pas GPS.",
    accent: "violet",
    mapEmphasis: "movement",
    mapCommandFamilies: [
      "macro_resilience_lane",
      "systemic_pressure_trace",
      "territorial_fragility_capsule",
      "corridor_dependency_audit",
      "collapse_propagation_read",
    ],
  },
  {
    slug: "relational-economic-continuity",
    poleChannel: "RELATIONAL_ORDERS",
    title: "Stabilité & continuité économique relationnelle",
    subtitle:
      "Couche 20.26 — continuité corridor, instabilité longue durée, récupération bornée — pas ERP, pas autopilot, pas marketplace.",
    accent: "emerald",
    mapEmphasis: "movement",
    mapCommandFamilies: [
      "continuity_stability_lane",
      "instability_temporal_trace",
      "recovery_projection_read",
      "long_term_dependency_audit",
      "systemic_continuity_pressure",
    ],
  },
  {
    slug: "relational-economic-sovereignty",
    poleChannel: "RELATIONAL_ORDERS",
    title: "Souveraineté économique & autonomie corridor",
    subtitle:
      "Couche 20.27 — autonomie relationnelle, dépendances critiques, captivité corridor — pas ERP, pas scoring public, pas système bancaire.",
    accent: "slate",
    mapEmphasis: "movement",
    mapCommandFamilies: [
      "sovereignty_autonomy_lane",
      "dependency_exposure_trace",
      "captivity_risk_read",
      "recovery_autonomy_projection",
      "systemic_dependency_audit",
    ],
  },
  {
    slug: "relational-economic-recovery",
    poleChannel: "RELATIONAL_ORDERS",
    title: "Planification de reprise économique corridor",
    subtitle:
      "Couche 20.29 — séquencement d’intervention, priorités et dépendances recovery — planification uniquement, pas autopilot ni exécution commerciale.",
    accent: "violet",
    mapEmphasis: "movement",
    mapCommandFamilies: [
      "recovery_planning_lane",
      "intervention_priority_trace",
      "dependency_recovery_map",
      "systemic_risk_containment_read",
      "corridor_recovery_projection",
    ],
  },
  {
    slug: "relational-economic-governance",
    poleChannel: "RELATIONAL_ORDERS",
    title: "Gouvernance économique multi-corridor",
    subtitle:
      "Couche 20.30 — coordination stratégique, conflits relationnels, équilibre réseau — intelligence gouvernance, pas autopilot.",
    accent: "violet",
    mapEmphasis: "movement",
    mapCommandFamilies: [
      "governance_coordination_lane",
      "conflict_detection_trace",
      "multi_corridor_balance_read",
      "systemic_tension_audit",
      "strategic_priority_arbitration",
    ],
  },
  {
    slug: "relational-economic-arbitration",
    poleChannel: "RELATIONAL_ORDERS",
    title: "Arbitrage économique relationnel",
    subtitle:
      "Couche 20.31 — résolution de conflits, scénarios déterministes, décisions journalisées — analyse et gouvernance, pas exécution.",
    accent: "violet",
    mapEmphasis: "movement",
    mapCommandFamilies: [
      "arbitration_conflict_lane",
      "scenario_resolution_trace",
      "systemic_impact_read",
      "human_decision_journal",
      "corridor_priority_arbitration",
    ],
  },
  {
    slug: "relational-economic-stabilization",
    poleChannel: "RELATIONAL_ORDERS",
    title: "Stabilisation économique multi-corridor",
    subtitle:
      "Couche 20.32 — résilience stratégique, corridors fragiles, exposition systémique — coordination analytique, pas autopilot.",
    accent: "violet",
    mapEmphasis: "movement",
    mapCommandFamilies: [
      "stabilization_resilience_lane",
      "fragile_corridor_trace",
      "systemic_exposure_read",
      "dependency_balance_audit",
      "strategic_stabilization_priority",
    ],
  },
  {
    slug: "relational-economic-monitoring",
    poleChannel: "RELATIONAL_ORDERS",
    title: "Supervision stratégique exécutive",
    subtitle:
      "Couche 20.33 — agrégation signaux, stabilité systémique, alertes stratégiques — gouvernance analytique, pas ERP ni autopilot.",
    accent: "violet",
    mapEmphasis: "movement",
    mapCommandFamilies: [
      "executive_supervision_lane",
      "systemic_risk_trace",
      "critical_corridor_watch",
      "strategic_alert_consolidation",
      "inter_pole_coordination_read",
    ],
  },
  {
    slug: "relational-executive-orchestration",
    poleChannel: "RELATIONAL_ORDERS",
    title: "Orchestration exécutive économique",
    subtitle:
      "Couche 20.34 — matrice de supervision stratégique multi-corridor, coordination et alignement — analytique, pas automate.",
    accent: "violet",
    mapEmphasis: "movement",
    mapCommandFamilies: [
      "executive_matrix_lane",
      "systemic_exposure_trace",
      "coordination_breakdown_read",
      "strategic_alignment_audit",
      "executive_dependency_supervision",
    ],
  },
  {
    slug: "relational-institutional-reporting",
    poleChannel: "RELATIONAL_ORDERS",
    title: "Reporting institutionnel économique",
    subtitle:
      "Couche 20.35 — briefs stratégiques déterministes, risques systémiques, lecture direction — institutionnel, pas IA générative.",
    accent: "violet",
    mapEmphasis: "movement",
    mapCommandFamilies: [
      "institutional_reporting_lane",
      "executive_brief_template",
      "systemic_risk_digest",
      "strategic_resilience_snapshot",
      "governance_brief_read",
    ],
  },
  {
    slug: "relational-strategic-intelligence",
    poleChannel: "RELATIONAL_ORDERS",
    title: "Intelligence stratégique consolidée",
    subtitle:
      "Couche 20.36 — synthèses exécutives déterministes, concentration systémique, cohérence réseau — consolidation, pas IA générative.",
    accent: "violet",
    mapEmphasis: "movement",
    mapCommandFamilies: [
      "strategic_consolidation_lane",
      "executive_synthesis_template",
      "systemic_concentration_digest",
      "network_resilience_snapshot",
      "governance_synthesis_read",
    ],
  },
  {
    slug: "relational-strategic-command",
    poleChannel: "RELATIONAL_ORDERS",
    title: "Command center stratégique relationnel",
    subtitle:
      "Couche 20.37 — grilles de supervision exécutive, pression systémique, concentration corridor — analytique institutionnel, pas ERP ni IA générative.",
    accent: "violet",
    mapEmphasis: "movement",
    mapCommandFamilies: [
      "strategic_command_grid_lane",
      "executive_supervision_template",
      "systemic_pressure_digest",
      "resilience_oversight_snapshot",
      "governance_command_read",
    ],
  },
  {
    slug: "relational-executive-operations",
    poleChannel: "RELATIONAL_ORDERS",
    title: "Opérations exécutives stratégiques",
    subtitle:
      "Couche 20.38 — matrices de supervision décisionnelle, pression exécutive, concentration systémique — supervision institutionnelle, pas ERP ni IA générative.",
    accent: "violet",
    mapEmphasis: "movement",
    mapCommandFamilies: [
      "executive_operations_matrix_lane",
      "decision_supervision_template",
      "systemic_concentration_digest",
      "resilience_operations_snapshot",
      "executive_balance_read",
    ],
  },
  {
    slug: "relational-executive-control-room",
    poleChannel: "RELATIONAL_ORDERS",
    title: "Salle de contrôle exécutive",
    subtitle:
      "Couche 20.39 — decision boards stratégiques, concentration systémique, résilience globale — supervision exécutive institutionnelle, pas ERP ni IA générative.",
    accent: "violet",
    mapEmphasis: "movement",
    mapCommandFamilies: [
      "executive_control_room_board_lane",
      "strategic_decision_board_template",
      "systemic_pressure_digest",
      "resilience_supervision_snapshot",
      "executive_balance_board_read",
    ],
  },
  {
    slug: "relational-executive-strategic-synthesis",
    poleChannel: "RELATIONAL_ORDERS",
    title: "Synthèse exécutive stratégique",
    subtitle:
      "Couche 20.40 — digests de supervision globale, exposition exécutive, pression systémique — consolidation institutionnelle, pas ERP ni IA générative.",
    accent: "violet",
    mapEmphasis: "movement",
    mapCommandFamilies: [
      "executive_synthesis_digest_lane",
      "strategic_alignment_digest_template",
      "systemic_pressure_consolidation",
      "resilience_synthesis_snapshot",
      "executive_balance_digest_read",
    ],
  },
  {
    slug: "relational-global-executive-supervision",
    poleChannel: "RELATIONAL_ORDERS",
    title: "Supervision exécutive globale",
    subtitle:
      "Couche 20.41 — matrices de coordination maître, pression exécutive, exposition systémique — supervision réseau institutionnelle, pas ERP ni IA générative.",
    accent: "violet",
    mapEmphasis: "movement",
    mapCommandFamilies: [
      "global_executive_supervision_matrix_lane",
      "strategic_network_matrix_template",
      "systemic_exposure_consolidation",
      "resilience_supervision_snapshot",
      "executive_balance_matrix_read",
    ],
  },
  {
    slug: "relational-strategic-observatory",
    poleChannel: "RELATIONAL_ORDERS",
    title: "Observatoire économique stratégique",
    subtitle:
      "Couche 20.42 — grilles de coordination macro, observation multi-corridors, pressions systémiques — analytique institutionnel, pas ERP ni IA générative.",
    accent: "violet",
    mapEmphasis: "movement",
    mapCommandFamilies: [
      "strategic_observatory_grid_lane",
      "macro_coordination_grid_template",
      "systemic_concentration_consolidation",
      "resilience_coordination_snapshot",
      "executive_alignment_grid_read",
    ],
  },
  {
    slug: "relational-macro-observatory-governance",
    poleChannel: "RELATIONAL_ORDERS",
    title: "Gouvernance macro-observatoire",
    subtitle:
      "Couche 20.43 — matrices de coordination réseau, gouvernance macro-corridors, équilibres territoriaux/sectoriels — analytique institutionnel, pas duplication command/synthesis.",
    accent: "violet",
    mapEmphasis: "movement",
    mapCommandFamilies: [
      "macro_observatory_governance_matrix_lane",
      "executive_coordination_matrix_template",
      "systemic_governance_concentration",
      "network_alignment_snapshot",
      "territorial_balance_matrix_read",
    ],
  },
  {
    slug: "relational-supply-flow",
    poleChannel: "RELATIONAL_ORDERS",
    title: "Intelligence des flux d’approvisionnement corridor",
    subtitle:
      "Couche 20.24 — continuité, pression, goulets, propagation systémique — pas TMS/WMS, pas tracking livraison, pas GPS.",
    accent: "amber",
    mapEmphasis: "movement",
    mapCommandFamilies: [
      "corridor_supply_flow_lane",
      "continuity_pressure_trace",
      "bottleneck_read_capsule",
      "dependency_chain_audit",
      "territorial_flow_balance_read",
    ],
  },
  {
    slug: "relational-operational-intelligence",
    poleChannel: "RELATIONAL_ORDERS",
    title: "Intelligence opérationnelle",
    subtitle:
      "SLA corridor, alertes opérationnelles, risques exécution (20.12) — pas KPI marketplace ni notation publique",
    accent: "cyan",
    mapEmphasis: "movement",
    mapCommandFamilies: [
      "corridor_sla_lane",
      "operational_risk_trace",
      "fulfillment_latency_capsule",
      "coordination_saturation_read",
      "corridor_degradation_audit",
    ],
  },
  {
    slug: "relational-fulfillment",
    poleChannel: "RELATIONAL_ORDERS",
    title: "Fulfillment relationnel",
    subtitle:
      "Post-exécution corridor (20.9) — preuve réception, validation partenaire, incidents — pas tracking colis grand public",
    accent: "cyan",
    mapEmphasis: "movement",
    mapCommandFamilies: [
      "corridor_fulfillment_lane",
      "reception_proof_trace",
      "partner_validation_capsule",
      "fulfillment_incident_audit",
      "relational_reception_compliance",
    ],
  },
  {
    slug: "relational-order-execution",
    poleChannel: "RELATIONAL_ORDERS",
    title: "Exécution commande relationnelle",
    subtitle:
      "Moteur d’exécution corridor (20.8) — préparation, acheminement, validation partenaire, diagnostics — pas tracking public ni marketplace",
    accent: "cyan",
    mapEmphasis: "movement",
    mapCommandFamilies: [
      "relational_execution_lane",
      "corridor_governance_bind",
      "partner_validation_trace",
      "execution_event_audit",
      "industrial_fulfillment_core",
    ],
  },
  {
    slug: "commercial-trust",
    poleChannel: "COMMERCIAL_TRUST",
    title: "Confiance commerciale relationnelle",
    subtitle:
      "Couche interne VENEXT — stabilité corridor, réactivité, signaux heuristiques (20.3) — pas réputation marketplace ni réseau social",
    accent: "slate",
    mapEmphasis: "network",
    mapCommandFamilies: [
      "corridor_reliability_read",
      "negotiation_stability_proxy",
      "sponsored_discovery_conversion_lane",
      "symbolic_reservation_alignment",
      "private_trust_diagnostics_capsule",
    ],
  },
  {
    slug: "corridor-intelligence",
    poleChannel: "CORRIDOR_INTELLIGENCE",
    title: "Intelligence corridor",
    subtitle:
      "Gouvernance relationnelle VENEXT — état corridor, signaux privés, diagnostics (20.4) — pas marketplace, pas classement public",
    accent: "violet",
    mapEmphasis: "network",
    mapCommandFamilies: [
      "corridor_state_machine_read",
      "private_corridor_signals_digest",
      "relational_governance_lane",
      "sponsored_corridor_conversion_trace",
      "corridor_health_heuristic_capsule",
    ],
  },
  {
    slug: "industrial-safety",
    poleChannel: "INDUSTRIAL_SAFETY",
    title: "Industrial safety",
    subtitle: "Incident command — hazard envelopes, hydrant geometry, muster",
    accent: "rose",
    mapEmphasis: "incident",
    mapCommandFamilies: [
      "industrial_incidents",
      "fire_risk_overlays",
      "emergency_response_layers",
      "hydrant_proximity",
      "hazardous_zones",
    ],
  },
];

export const POLE_SLUGS: PoleSlug[] = POLE_REGISTRY.map((p) => p.slug);

export function getPoleEntry(slug: string): PoleRegistryEntry | undefined {
  return POLE_REGISTRY.find((p) => p.slug === slug);
}
