import type { RelationalAnalyticDepth } from "./relational-analytic-depth";

export type RelationalLayerRegistryEntry = {
  level: 5;
  instruction: string;
  order: number;
  layerSlug: string;
  moduleFolder: string;
  depth: RelationalAnalyticDepth;
  ingestionService: string;
  syncMethod: string;
  chainsToSyncMethod: string | null;
  controllerPrefix: string;
  realtimeNamespace: string;
  featureFlagEnabled: string;
  featureFlagRealtime: string;
  prismaNodeModel: string;
  terminal: boolean;
};

export const RELATIONAL_LAYER_REGISTRY: readonly RelationalLayerRegistryEntry[] = [
  {
    level: 5,
    instruction: "20.28",
    order: 1,
    layerSlug: "relational-economic-sovereignty",
    moduleFolder: "relational-economic-sovereignty",
    depth: "macro",
    ingestionService: "RelationalEconomicSovereigntyIngestionService",
    syncMethod: "syncEconomicSovereigntyState",
    chainsToSyncMethod: "syncEconomicRecoveryState",
    controllerPrefix: "relational-economic-sovereignty",
    realtimeNamespace: "relational.sovereignty.",
    featureFlagEnabled: "relational_economic_sovereignty_enabled",
    featureFlagRealtime: "relational_economic_sovereignty_realtime_enabled",
    prismaNodeModel: "RelationalEconomicSovereigntyNode",
    terminal: false,
  },
  {
    level: 5,
    instruction: "20.29",
    order: 2,
    layerSlug: "relational-economic-recovery",
    moduleFolder: "relational-economic-recovery",
    depth: "macro",
    ingestionService: "RelationalEconomicRecoveryIngestionService",
    syncMethod: "syncEconomicRecoveryState",
    chainsToSyncMethod: "syncEconomicGovernanceState",
    controllerPrefix: "relational-economic-recovery",
    realtimeNamespace: "relational.recovery.",
    featureFlagEnabled: "relational_economic_recovery_enabled",
    featureFlagRealtime: "relational_economic_recovery_realtime_enabled",
    prismaNodeModel: "RelationalEconomicRecoveryPlan",
    terminal: false,
  },
  {
    level: 5,
    instruction: "20.30",
    order: 3,
    layerSlug: "relational-economic-governance",
    moduleFolder: "relational-economic-governance",
    depth: "macro",
    ingestionService: "RelationalEconomicGovernanceIngestionService",
    syncMethod: "syncEconomicGovernanceState",
    chainsToSyncMethod: "syncEconomicArbitrationState",
    controllerPrefix: "relational-economic-governance",
    realtimeNamespace: "relational.governance.",
    featureFlagEnabled: "relational_economic_governance_enabled",
    featureFlagRealtime: "relational_economic_governance_realtime_enabled",
    prismaNodeModel: "RelationalEconomicGovernanceNode",
    terminal: false,
  },
  {
    level: 5,
    instruction: "20.31",
    order: 4,
    layerSlug: "relational-economic-arbitration",
    moduleFolder: "relational-economic-arbitration",
    depth: "macro",
    ingestionService: "RelationalEconomicArbitrationIngestionService",
    syncMethod: "syncEconomicArbitrationState",
    chainsToSyncMethod: "syncEconomicStabilizationState",
    controllerPrefix: "relational-economic-arbitration",
    realtimeNamespace: "relational.arbitration.",
    featureFlagEnabled: "relational_economic_arbitration_enabled",
    featureFlagRealtime: "relational_economic_arbitration_realtime_enabled",
    prismaNodeModel: "RelationalEconomicArbitrationCase",
    terminal: false,
  },
  {
    level: 5,
    instruction: "20.32",
    order: 5,
    layerSlug: "relational-economic-stabilization",
    moduleFolder: "relational-economic-stabilization",
    depth: "macro",
    ingestionService: "RelationalEconomicStabilizationIngestionService",
    syncMethod: "syncEconomicStabilizationState",
    chainsToSyncMethod: "syncEconomicMonitoringState",
    controllerPrefix: "relational-economic-stabilization",
    realtimeNamespace: "relational.stabilization.",
    featureFlagEnabled: "relational_economic_stabilization_enabled",
    featureFlagRealtime: "relational_economic_stabilization_realtime_enabled",
    prismaNodeModel: "RelationalEconomicStabilizationNode",
    terminal: false,
  },
  {
    level: 5,
    instruction: "20.33",
    order: 6,
    layerSlug: "relational-economic-monitoring",
    moduleFolder: "relational-economic-monitoring",
    depth: "executive",
    ingestionService: "RelationalEconomicMonitoringIngestionService",
    syncMethod: "syncEconomicMonitoringState",
    chainsToSyncMethod: "syncExecutiveOrchestrationState",
    controllerPrefix: "relational-economic-monitoring",
    realtimeNamespace: "relational.monitoring.",
    featureFlagEnabled: "relational_economic_monitoring_enabled",
    featureFlagRealtime: "relational_economic_monitoring_realtime_enabled",
    prismaNodeModel: "RelationalEconomicMonitoringNode",
    terminal: false,
  },
  {
    level: 5,
    instruction: "20.34",
    order: 7,
    layerSlug: "relational-executive-orchestration",
    moduleFolder: "relational-executive-orchestration",
    depth: "executive",
    ingestionService: "RelationalExecutiveOrchestrationIngestionService",
    syncMethod: "syncExecutiveOrchestrationState",
    chainsToSyncMethod: "syncInstitutionalReportingState",
    controllerPrefix: "relational-executive-orchestration",
    realtimeNamespace: "relational.executive_orchestration.",
    featureFlagEnabled: "relational_executive_orchestration_enabled",
    featureFlagRealtime: "relational_executive_orchestration_realtime_enabled",
    prismaNodeModel: "RelationalExecutiveOrchestrationNode",
    terminal: false,
  },
  {
    level: 5,
    instruction: "20.35",
    order: 8,
    layerSlug: "relational-institutional-reporting",
    moduleFolder: "relational-institutional-reporting",
    depth: "executive",
    ingestionService: "RelationalInstitutionalReportingIngestionService",
    syncMethod: "syncInstitutionalReportingState",
    chainsToSyncMethod: "syncStrategicIntelligenceState",
    controllerPrefix: "relational-institutional-reporting",
    realtimeNamespace: "relational.institutional_reporting.",
    featureFlagEnabled: "relational_institutional_reporting_enabled",
    featureFlagRealtime: "relational_institutional_reporting_realtime_enabled",
    prismaNodeModel: "RelationalInstitutionalReportingNode",
    terminal: false,
  },
  {
    level: 5,
    instruction: "20.36",
    order: 9,
    layerSlug: "relational-strategic-intelligence",
    moduleFolder: "relational-strategic-intelligence",
    depth: "strategic",
    ingestionService: "RelationalStrategicIntelligenceIngestionService",
    syncMethod: "syncStrategicIntelligenceState",
    chainsToSyncMethod: "syncStrategicCommandState",
    controllerPrefix: "relational-strategic-intelligence",
    realtimeNamespace: "relational.strategic_intelligence.",
    featureFlagEnabled: "relational_strategic_intelligence_enabled",
    featureFlagRealtime: "relational_strategic_intelligence_realtime_enabled",
    prismaNodeModel: "RelationalStrategicIntelligenceNode",
    terminal: false,
  },
  {
    level: 5,
    instruction: "20.37",
    order: 10,
    layerSlug: "relational-strategic-command",
    moduleFolder: "relational-strategic-command",
    depth: "strategic",
    ingestionService: "RelationalStrategicCommandIngestionService",
    syncMethod: "syncStrategicCommandState",
    chainsToSyncMethod: "syncExecutiveOperationsState",
    controllerPrefix: "relational-strategic-command",
    realtimeNamespace: "relational.strategic_command.",
    featureFlagEnabled: "relational_strategic_command_enabled",
    featureFlagRealtime: "relational_strategic_command_realtime_enabled",
    prismaNodeModel: "RelationalStrategicCommandNode",
    terminal: false,
  },
  {
    level: 5,
    instruction: "20.38",
    order: 11,
    layerSlug: "relational-executive-operations",
    moduleFolder: "relational-executive-operations",
    depth: "executive",
    ingestionService: "RelationalExecutiveOperationsIngestionService",
    syncMethod: "syncExecutiveOperationsState",
    chainsToSyncMethod: "syncExecutiveControlRoomState",
    controllerPrefix: "relational-executive-operations",
    realtimeNamespace: "relational.executive_operations.",
    featureFlagEnabled: "relational_executive_operations_enabled",
    featureFlagRealtime: "relational_executive_operations_realtime_enabled",
    prismaNodeModel: "RelationalExecutiveOperationsNode",
    terminal: false,
  },
  {
    level: 5,
    instruction: "20.39",
    order: 12,
    layerSlug: "relational-executive-control-room",
    moduleFolder: "relational-executive-control-room",
    depth: "executive",
    ingestionService: "RelationalExecutiveControlRoomIngestionService",
    syncMethod: "syncExecutiveControlRoomState",
    chainsToSyncMethod: "syncExecutiveStrategicSynthesisState",
    controllerPrefix: "relational-executive-control-room",
    realtimeNamespace: "relational.executive_control_room.",
    featureFlagEnabled: "relational_executive_control_room_enabled",
    featureFlagRealtime: "relational_executive_control_room_realtime_enabled",
    prismaNodeModel: "RelationalExecutiveControlRoomNode",
    terminal: false,
  },
  {
    level: 5,
    instruction: "20.40",
    order: 13,
    layerSlug: "relational-executive-strategic-synthesis",
    moduleFolder: "relational-executive-strategic-synthesis",
    depth: "executive",
    ingestionService: "RelationalExecutiveStrategicSynthesisIngestionService",
    syncMethod: "syncExecutiveStrategicSynthesisState",
    chainsToSyncMethod: "syncGlobalExecutiveSupervisionState",
    controllerPrefix: "relational-executive-strategic-synthesis",
    realtimeNamespace: "relational.executive_strategic_synthesis.",
    featureFlagEnabled: "relational_executive_strategic_synthesis_enabled",
    featureFlagRealtime: "relational_executive_strategic_synthesis_realtime_enabled",
    prismaNodeModel: "RelationalExecutiveStrategicSynthesisNode",
    terminal: false,
  },
  {
    level: 5,
    instruction: "20.41",
    order: 14,
    layerSlug: "relational-global-executive-supervision",
    moduleFolder: "relational-global-executive-supervision",
    depth: "observatory",
    ingestionService: "RelationalGlobalExecutiveSupervisionIngestionService",
    syncMethod: "syncGlobalExecutiveSupervisionState",
    chainsToSyncMethod: "syncStrategicObservatoryState",
    controllerPrefix: "relational-global-executive-supervision",
    realtimeNamespace: "relational.global_executive_supervision.",
    featureFlagEnabled: "relational_global_executive_supervision_enabled",
    featureFlagRealtime: "relational_global_executive_supervision_realtime_enabled",
    prismaNodeModel: "RelationalGlobalExecutiveSupervisionNode",
    terminal: false,
  },
  {
    level: 5,
    instruction: "20.42",
    order: 15,
    layerSlug: "relational-strategic-observatory",
    moduleFolder: "relational-strategic-observatory",
    depth: "observatory",
    ingestionService: "RelationalStrategicObservatoryIngestionService",
    syncMethod: "syncStrategicObservatoryState",
    chainsToSyncMethod: "syncMacroObservatoryGovernanceState",
    controllerPrefix: "relational-strategic-observatory",
    realtimeNamespace: "relational.strategic_observatory.",
    featureFlagEnabled: "relational_strategic_observatory_enabled",
    featureFlagRealtime: "relational_strategic_observatory_realtime_enabled",
    prismaNodeModel: "RelationalStrategicObservatoryNode",
    terminal: false,
  },
  {
    level: 5,
    instruction: "20.43",
    order: 16,
    layerSlug: "relational-macro-observatory-governance",
    moduleFolder: "relational-macro-observatory-governance",
    depth: "observatory",
    ingestionService: "RelationalMacroObservatoryGovernanceIngestionService",
    syncMethod: "syncMacroObservatoryGovernanceState",
    chainsToSyncMethod: null,
    controllerPrefix: "relational-macro-observatory-governance",
    realtimeNamespace: "relational.macro_observatory_governance.",
    featureFlagEnabled: "relational_macro_observatory_governance_enabled",
    featureFlagRealtime: "relational_macro_observatory_governance_realtime_enabled",
    prismaNodeModel: "RelationalMacroObservatoryGovernanceNode",
    terminal: true,
  },
] as const;
