"use client";

import { useEffect, useState } from "react";

export type IndustrialFlagsState = Record<string, boolean | undefined>;

const IS_PRODUCTION = process.env.NODE_ENV === "production";

/** Safe production defaults — unknown flags stay off until the server hydrates. */
const PRODUCTION_DEFAULTS: IndustrialFlagsState = {
  industrial_poles_enabled: false,
  logistics_map_enabled: false,
  industrial_safety_enabled: false,
  sponsored_products_enabled: false,
  relationship_graph_enabled: false,
  contact_sync_enabled: false,
  qr_relationship_enabled: false,
  commercial_identity_enabled: false,
  wallet_enabled: false,
  payments_enabled: false,
  group_buying_enabled: false,
  voice_messaging_enabled: false,
  sponsored_visibility_enabled: false,
  ai_assistant_enabled: false,
  realtime_signals_enabled: false,
  weather_signals_enabled: false,
  edge_sync_enabled: false,
  strategic_intelligence_enabled: false,
  strategic_ai_enabled: false,
  territory_map_enabled: false,
  market_pressure_enabled: false,
  commercial_network_enabled: false,
  sponsorship_observatory_enabled: false,
  retailer_radar_enabled: false,
  relationship_stability_enabled: false,
  commercial_network_ai_enabled: false,
  marketing_activation_enabled: false,
  sponsorship_pressure_enabled: false,
  retailer_engagement_enabled: false,
  product_momentum_enabled: false,
  marketing_activation_ai_enabled: false,
  order_adv_enabled: false,
  conversational_commerce_enabled: false,
  negotiation_intelligence_enabled: false,
  reservation_allocation_enabled: false,
  order_adv_ai_enabled: false,
  supply_logistics_enabled: false,
  territory_flow_enabled: false,
  shipment_health_enabled: false,
  warehouse_pressure_enabled: false,
  supply_ai_enabled: false,
  finance_collections_enabled: false,
  payment_pressure_enabled: false,
  wallet_liquidity_enabled: false,
  credit_risk_enabled: false,
  finance_ai_enabled: false,
  data_intelligence_enabled: false,
  predictive_signals_enabled: false,
  graph_intelligence_enabled: false,
  decision_simulation_enabled: false,
  data_intelligence_ai_enabled: false,
  economic_propagation_enabled: false,
  propagation_simulation_enabled: false,
  cross_pole_propagation_enabled: false,
  economic_shock_detection_enabled: false,
  economic_memory_enabled: false,
  crisis_signature_enabled: false,
  temporal_analysis_enabled: false,
  economic_memory_ai_enabled: false,
  economic_scenarios_enabled: false,
  scenario_risk_enabled: false,
  scenario_memory_enabled: false,
  scenario_stabilization_enabled: false,
  economic_scenarios_ai_enabled: false,
  economic_coordination_enabled: false,
  coordination_conflict_enabled: false,
  coordination_memory_enabled: false,
  coordination_orchestration_enabled: false,
  economic_escalation_enabled: false,
  economic_command_enabled: false,
  economic_command_risk_enabled: false,
  economic_command_arbitration_enabled: false,
  economic_command_tension_enabled: false,
  economic_command_realtime_enabled: false,
  industrial_situation_room_enabled: false,
  industrial_situation_room_realtime_enabled: false,
  industrial_operational_continuity_enabled: false,
  industrial_operational_continuity_realtime_enabled: false,
  industrial_evidence_enabled: false,
  industrial_evidence_realtime_enabled: false,
  industrial_evidence_trace_enabled: false,
  industrial_evidence_limitations_enabled: false,
  commercial_relationship_graph_enabled: false,
  commercial_relationship_graph_realtime_enabled: false,
  commercial_relationship_graph_coverage_enabled: false,
  commercial_relationship_graph_chains_enabled: false,
  relational_catalog_enabled: false,
  relational_catalog_realtime_enabled: false,
  relational_cart_enabled: false,
  relational_cart_realtime_enabled: false,
  relational_cart_review_enabled: false,
  relational_cart_dual_confirmation_enabled: false,
  relational_cart_lock_enabled: false,
  relational_cart_direct_catalog_enabled: false,
  relational_cart_direct_catalog_realtime_enabled: false,
  relational_orders_enabled: false,
  relational_orders_realtime_enabled: false,
  relational_order_execution_enabled: false,
  relational_fulfillment_enabled: false,
  relational_fulfillment_realtime_enabled: false,
  relational_fulfillment_proof_enabled: false,
  relational_fulfillment_incident_resolution_enabled: false,
  relational_fulfillment_coordination_enabled: false,
  relational_fulfillment_coordination_realtime_enabled: false,
  relational_operational_intelligence_enabled: false,
  relational_operational_realtime_enabled: false,
  relational_predictive_risk_enabled: false,
  relational_predictive_realtime_enabled: false,
  relational_operational_recommendation_enabled: false,
  relational_operational_recommendation_realtime_enabled: false,
  relational_operational_orchestration_enabled: false,
  relational_operational_orchestration_realtime_enabled: false,
  relational_operational_simulation_enabled: false,
  relational_operational_simulation_realtime_enabled: false,
  relational_scenario_review_enabled: false,
  relational_scenario_review_realtime_enabled: false,
  relational_strategic_memory_enabled: false,
  relational_strategic_memory_realtime_enabled: false,
  relational_economic_signal_graph_enabled: false,
  relational_economic_signal_graph_realtime_enabled: false,
  relational_economic_command_center_enabled: false,
  relational_economic_command_center_realtime_enabled: false,
  relational_economic_pressure_enabled: false,
  relational_economic_pressure_realtime_enabled: false,
  relational_geo_economic_enabled: false,
  relational_geo_economic_realtime_enabled: false,
  relational_sector_intelligence_enabled: false,
  relational_sector_realtime_enabled: false,
  relational_supply_flow_enabled: false,
  relational_supply_flow_realtime_enabled: false,
  relational_macro_economic_enabled: false,
  relational_macro_economic_realtime_enabled: false,
  relational_economic_continuity_enabled: false,
  relational_economic_continuity_realtime_enabled: false,
  relational_economic_sovereignty_enabled: false,
  relational_economic_sovereignty_realtime_enabled: false,
  relational_economic_recovery_enabled: false,
  relational_economic_recovery_realtime_enabled: false,
  relational_economic_governance_enabled: false,
  relational_economic_governance_realtime_enabled: false,
  relational_economic_arbitration_enabled: false,
  relational_economic_arbitration_realtime_enabled: false,
  relational_economic_stabilization_enabled: false,
  relational_economic_stabilization_realtime_enabled: false,
  relational_economic_monitoring_enabled: false,
  relational_economic_monitoring_realtime_enabled: false,
  relational_executive_orchestration_enabled: false,
  relational_executive_orchestration_realtime_enabled: false,
  relational_institutional_reporting_enabled: false,
  relational_institutional_reporting_realtime_enabled: false,
  relational_strategic_intelligence_enabled: false,
  relational_strategic_intelligence_realtime_enabled: false,
  relational_strategic_command_enabled: false,
  relational_strategic_command_realtime_enabled: false,
  relational_executive_operations_enabled: false,
  relational_executive_operations_realtime_enabled: false,
  relational_executive_control_room_enabled: false,
  relational_executive_control_room_realtime_enabled: false,
  relational_executive_strategic_synthesis_enabled: false,
  relational_executive_strategic_synthesis_realtime_enabled: false,
  relational_global_executive_supervision_enabled: false,
  relational_global_executive_supervision_realtime_enabled: false,
  relational_strategic_observatory_enabled: false,
  relational_strategic_observatory_realtime_enabled: false,
  relational_macro_observatory_governance_enabled: false,
  relational_macro_observatory_governance_realtime_enabled: false,
  commercial_trust_layer_enabled: false,
  commercial_trust_realtime_enabled: false,
  corridor_intelligence_layer_enabled: false,
  corridor_intelligence_realtime_enabled: false,
  producer_industrial_web_enabled: false,
  producer_industrial_live_data_enabled: false,
  producer_relational_commercial_workspace_enabled: false,
  producer_order_fulfillment_workspace_enabled: false,
  producer_commercial_mail_enabled: false,
  professional_commercial_network_enabled: false,
  producer_partner_network_enabled: false,
  producer_catalog_workspace_enabled: false,
  producer_territory_distribution_workspace_enabled: false,
  producer_marketing_activation_workspace_enabled: false,
  producer_supply_logistics_workspace_enabled: false,
  producer_finance_collections_workspace_enabled: false,
  producer_data_intelligence_workspace_enabled: false,
  grossiste_b_mobile_enabled: false,
  grossiste_b_commerce_messaging_enabled: false,
  detaillant_mobile_enabled: false,
  detaillant_commerce_messaging_enabled: false,
  grossiste_a_web_enabled: false,
  grossiste_a_commerce_messaging_enabled: false,
  commerce_messaging_enabled: false,
  commerce_conversation_governance_enabled: false,
  commerce_wallet_enabled: false,
  commerce_partner_payments_enabled: false,
  commerce_hybrid_settlement_enabled: false,
  commerce_manual_confirmation_enabled: false,
  producer_wallet_enabled: false,
  grossiste_a_wallet_enabled: false,
  grossiste_b_wallet_enabled: false,
  detaillant_wallet_enabled: false,
  commerce_linked_context_enabled: false,
  commerce_linked_timeline_enabled: false,
  commercial_network_discovery_enabled: false,
  commercial_auto_accept_enabled: false,
  commercial_contact_first_identity_enabled: false,
  commercial_activity_based_suggestions_enabled: false,
  sponsored_catalog_discovery_enabled: false,
  partner_catalog_visibility_enabled: false,
  terrain_quick_onboarding_enabled: false,
  terrain_pseudo_identity_enabled: false,
  relational_order_orchestration_enabled: false,
  commercial_delivery_flow_enabled: false,
  commercial_reception_confirmation_enabled: false,
  commercial_delivery_activity_enabled: false,
  commercial_settlement_flow_enabled: false,
  commerce_foundation_guardrails_enabled: false,
  commerce_navigation_consistency_enabled: false,
  commerce_anti_erp_wording_enabled: false,
  commercial_relationship_governance_enabled: false,
  commercial_multi_level_network_enabled: false,
  commercial_relationship_context_enabled: false,
  commercial_context_routing_enabled: false,
  commercial_context_history_enabled: false,
  commercial_cross_module_navigation_enabled: false,
  venext_i18n_enabled: false,
  venext_rtl_enabled: false,
  venext_multilingual_guardrails_enabled: false,
  venext_auth_foundation_enabled: false,
  venext_session_restore_enabled: false,
  venext_profile_foundation_enabled: false,
  terrain_unlimited_session_enabled: false,
  wallet_adaptive_security_enabled: false,
  wallet_bceao_kyc_enabled: false,
  wallet_biometric_unlock_enabled: false,
  wallet_instant_background_lock_enabled: false,
  wallet_ultra_short_timeout_enabled: false,
  venext_backend_persistence_enabled: false,
  venext_bff_routes_enabled: false,
  venext_live_data_fallback_enabled: false,
  commerce_notifications_enabled: false,
  commerce_notification_preferences_enabled: false,
  commerce_notification_context_routing_enabled: false,
  commercial_activity_feed_enabled: false,
  commercial_activity_timeline_enabled: false,
  commercial_activity_grouping_enabled: false,
  commerce_offline_foundation_enabled: false,
  commerce_offline_sync_enabled: false,
  commerce_offline_queue_enabled: false,
  commerce_access_control_enabled: false,
  commerce_visibility_guard_enabled: false,
  commerce_backend_access_guard_enabled: false,
  commerce_ux_harmony_enabled: false,
  commerce_performance_foundation_enabled: false,
  commerce_secure_cleanup_enabled: false,
  commerce_light_virtualization_enabled: false,
  commerce_secure_wallet_navigation_enabled: false,
  commerce_humanized_errors_enabled: false,
  enterprise_governance_enabled: false,
  enterprise_secure_channels_enabled: false,
  enterprise_controlled_onboarding_enabled: false,
  enterprise_security_governance_enabled: false,
  enterprise_archive_workflow_enabled: false,
  enterprise_internal_security_enabled: false,
  grossiste_a_partner_network_enabled: false,
};

/** Align with `prisma/seed.ts` global flags for local/demo UX (Instruction 9B). */
const DEV_SEED_ALIGNED_DEFAULTS: IndustrialFlagsState = {
  ...PRODUCTION_DEFAULTS,
  industrial_poles_enabled: true,
  logistics_map_enabled: true,
  industrial_safety_enabled: true,
  sponsored_products_enabled: true,
  relationship_graph_enabled: true,
  contact_sync_enabled: true,
  qr_relationship_enabled: true,
  commercial_identity_enabled: true,
  wallet_enabled: true,
  payments_enabled: true,
  voice_messaging_enabled: true,
  sponsored_visibility_enabled: true,
  ai_assistant_enabled: true,
  realtime_signals_enabled: true,
  weather_signals_enabled: true,
  edge_sync_enabled: true,
  strategic_intelligence_enabled: true,
  strategic_ai_enabled: true,
  territory_map_enabled: true,
  market_pressure_enabled: true,
  commercial_network_enabled: true,
  sponsorship_observatory_enabled: true,
  retailer_radar_enabled: true,
  relationship_stability_enabled: true,
  commercial_network_ai_enabled: true,
  marketing_activation_enabled: true,
  sponsorship_pressure_enabled: true,
  retailer_engagement_enabled: true,
  product_momentum_enabled: true,
  marketing_activation_ai_enabled: true,
  group_buying_enabled: true,
  order_adv_enabled: true,
  conversational_commerce_enabled: true,
  negotiation_intelligence_enabled: true,
  reservation_allocation_enabled: true,
  order_adv_ai_enabled: true,
  supply_logistics_enabled: true,
  territory_flow_enabled: true,
  shipment_health_enabled: true,
  warehouse_pressure_enabled: true,
  supply_ai_enabled: true,
  finance_collections_enabled: true,
  payment_pressure_enabled: true,
  wallet_liquidity_enabled: true,
  credit_risk_enabled: true,
  finance_ai_enabled: true,
  data_intelligence_enabled: true,
  predictive_signals_enabled: true,
  graph_intelligence_enabled: true,
  decision_simulation_enabled: true,
  data_intelligence_ai_enabled: true,
  economic_propagation_enabled: true,
  propagation_simulation_enabled: true,
  cross_pole_propagation_enabled: true,
  economic_shock_detection_enabled: true,
  economic_memory_enabled: true,
  crisis_signature_enabled: true,
  temporal_analysis_enabled: true,
  economic_memory_ai_enabled: true,
  economic_scenarios_enabled: true,
  scenario_risk_enabled: true,
  scenario_memory_enabled: true,
  scenario_stabilization_enabled: true,
  economic_scenarios_ai_enabled: true,
  economic_coordination_enabled: true,
  coordination_conflict_enabled: true,
  coordination_memory_enabled: true,
  coordination_orchestration_enabled: true,
  economic_escalation_enabled: true,
  economic_command_enabled: true,
  economic_command_risk_enabled: true,
  economic_command_arbitration_enabled: true,
  economic_command_tension_enabled: true,
  economic_command_realtime_enabled: true,
  industrial_situation_room_enabled: true,
  industrial_situation_room_realtime_enabled: true,
  industrial_operational_continuity_enabled: true,
  industrial_operational_continuity_realtime_enabled: true,
  industrial_evidence_enabled: true,
  industrial_evidence_realtime_enabled: true,
  industrial_evidence_trace_enabled: true,
  industrial_evidence_limitations_enabled: true,
  commercial_relationship_graph_enabled: true,
  commercial_relationship_graph_realtime_enabled: true,
  commercial_relationship_graph_coverage_enabled: true,
  commercial_relationship_graph_chains_enabled: true,
  relational_catalog_enabled: true,
  relational_catalog_realtime_enabled: true,
  relational_cart_enabled: true,
  relational_cart_realtime_enabled: true,
  relational_cart_review_enabled: true,
  relational_cart_dual_confirmation_enabled: true,
  relational_cart_lock_enabled: true,
  relational_cart_direct_catalog_enabled: true,
  relational_cart_direct_catalog_realtime_enabled: true,
  relational_orders_enabled: true,
  relational_orders_realtime_enabled: true,
  relational_order_execution_enabled: true,
  relational_fulfillment_enabled: true,
  relational_fulfillment_realtime_enabled: true,
  relational_fulfillment_proof_enabled: true,
  relational_fulfillment_incident_resolution_enabled: true,
  relational_fulfillment_coordination_enabled: true,
  relational_fulfillment_coordination_realtime_enabled: true,
  relational_operational_intelligence_enabled: true,
  relational_operational_realtime_enabled: true,
  relational_predictive_risk_enabled: true,
  relational_predictive_realtime_enabled: true,
  relational_operational_recommendation_enabled: true,
  relational_operational_recommendation_realtime_enabled: true,
  relational_operational_orchestration_enabled: true,
  relational_operational_orchestration_realtime_enabled: true,
  relational_operational_simulation_enabled: true,
  relational_operational_simulation_realtime_enabled: true,
  relational_scenario_review_enabled: true,
  relational_scenario_review_realtime_enabled: true,
  relational_strategic_memory_enabled: true,
  relational_strategic_memory_realtime_enabled: true,
  relational_economic_signal_graph_enabled: true,
  relational_economic_signal_graph_realtime_enabled: true,
  relational_economic_command_center_enabled: true,
  relational_economic_command_center_realtime_enabled: true,
  relational_economic_pressure_enabled: true,
  relational_economic_pressure_realtime_enabled: true,
  relational_geo_economic_enabled: true,
  relational_geo_economic_realtime_enabled: true,
  relational_sector_intelligence_enabled: true,
  relational_sector_realtime_enabled: true,
  relational_supply_flow_enabled: true,
  relational_supply_flow_realtime_enabled: true,
  relational_macro_economic_enabled: true,
  relational_macro_economic_realtime_enabled: true,
  relational_economic_continuity_enabled: true,
  relational_economic_continuity_realtime_enabled: true,
  relational_economic_sovereignty_enabled: true,
  relational_economic_sovereignty_realtime_enabled: true,
  relational_economic_recovery_enabled: true,
  relational_economic_recovery_realtime_enabled: true,
  relational_economic_governance_enabled: true,
  relational_economic_governance_realtime_enabled: true,
  relational_economic_arbitration_enabled: true,
  relational_economic_arbitration_realtime_enabled: true,
  relational_economic_stabilization_enabled: true,
  relational_economic_stabilization_realtime_enabled: true,
  relational_economic_monitoring_enabled: true,
  relational_economic_monitoring_realtime_enabled: true,
  relational_executive_orchestration_enabled: true,
  relational_executive_orchestration_realtime_enabled: true,
  relational_institutional_reporting_enabled: true,
  relational_institutional_reporting_realtime_enabled: true,
  relational_strategic_intelligence_enabled: true,
  relational_strategic_intelligence_realtime_enabled: true,
  relational_strategic_command_enabled: true,
  relational_strategic_command_realtime_enabled: true,
  relational_executive_operations_enabled: true,
  relational_executive_operations_realtime_enabled: true,
  relational_executive_control_room_enabled: true,
  relational_executive_control_room_realtime_enabled: true,
  relational_executive_strategic_synthesis_enabled: true,
  relational_executive_strategic_synthesis_realtime_enabled: true,
  relational_global_executive_supervision_enabled: true,
  relational_global_executive_supervision_realtime_enabled: true,
  relational_strategic_observatory_enabled: true,
  relational_strategic_observatory_realtime_enabled: true,
  relational_macro_observatory_governance_enabled: true,
  relational_macro_observatory_governance_realtime_enabled: true,
  commercial_trust_layer_enabled: true,
  commercial_trust_realtime_enabled: true,
  corridor_intelligence_layer_enabled: true,
  corridor_intelligence_realtime_enabled: true,
  producer_industrial_web_enabled: true,
  producer_industrial_live_data_enabled: true,
  producer_relational_commercial_workspace_enabled: true,
  producer_order_fulfillment_workspace_enabled: true,
  producer_commercial_mail_enabled: true,
  professional_commercial_network_enabled: true,
  producer_partner_network_enabled: true,
  grossiste_a_partner_network_enabled: true,
  producer_catalog_workspace_enabled: true,
  producer_territory_distribution_workspace_enabled: true,
  producer_marketing_activation_workspace_enabled: true,
  producer_supply_logistics_workspace_enabled: true,
  producer_finance_collections_workspace_enabled: true,
  producer_data_intelligence_workspace_enabled: true,
  grossiste_b_mobile_enabled: true,
  grossiste_b_commerce_messaging_enabled: true,
  detaillant_mobile_enabled: true,
  detaillant_commerce_messaging_enabled: true,
  grossiste_a_web_enabled: true,
  grossiste_a_commerce_messaging_enabled: true,
  commerce_messaging_enabled: true,
  commerce_conversation_governance_enabled: true,
  commerce_wallet_enabled: true,
  commerce_partner_payments_enabled: true,
  commerce_hybrid_settlement_enabled: true,
  commerce_manual_confirmation_enabled: true,
  producer_wallet_enabled: true,
  grossiste_a_wallet_enabled: true,
  grossiste_b_wallet_enabled: true,
  detaillant_wallet_enabled: true,
  commerce_linked_context_enabled: true,
  commerce_linked_timeline_enabled: true,
  commercial_network_discovery_enabled: true,
  commercial_auto_accept_enabled: true,
  commercial_contact_first_identity_enabled: true,
  commercial_activity_based_suggestions_enabled: true,
  sponsored_catalog_discovery_enabled: true,
  partner_catalog_visibility_enabled: true,
  terrain_quick_onboarding_enabled: true,
  terrain_pseudo_identity_enabled: true,
  relational_order_orchestration_enabled: true,
  commercial_delivery_flow_enabled: true,
  commercial_reception_confirmation_enabled: true,
  commercial_delivery_activity_enabled: true,
  commercial_settlement_flow_enabled: true,
  commerce_foundation_guardrails_enabled: true,
  commerce_navigation_consistency_enabled: true,
  commerce_anti_erp_wording_enabled: true,
  commercial_relationship_governance_enabled: true,
  commercial_multi_level_network_enabled: true,
  commercial_relationship_context_enabled: true,
  commercial_context_routing_enabled: true,
  commercial_context_history_enabled: true,
  commercial_cross_module_navigation_enabled: true,
  venext_i18n_enabled: true,
  venext_rtl_enabled: true,
  venext_multilingual_guardrails_enabled: true,
  venext_auth_foundation_enabled: true,
  venext_session_restore_enabled: true,
  venext_profile_foundation_enabled: true,
  terrain_unlimited_session_enabled: true,
  wallet_adaptive_security_enabled: true,
  wallet_bceao_kyc_enabled: true,
  wallet_biometric_unlock_enabled: true,
  wallet_instant_background_lock_enabled: true,
  wallet_ultra_short_timeout_enabled: true,
  venext_backend_persistence_enabled: true,
  venext_bff_routes_enabled: true,
  venext_live_data_fallback_enabled: true,
  commerce_notifications_enabled: true,
  commerce_notification_preferences_enabled: true,
  commerce_notification_context_routing_enabled: true,
  commercial_activity_feed_enabled: true,
  commercial_activity_timeline_enabled: true,
  commercial_activity_grouping_enabled: true,
  commerce_offline_foundation_enabled: true,
  commerce_offline_sync_enabled: true,
  commerce_offline_queue_enabled: true,
  commerce_access_control_enabled: true,
  commerce_visibility_guard_enabled: true,
  commerce_backend_access_guard_enabled: true,
  commerce_ux_harmony_enabled: true,
  commerce_performance_foundation_enabled: true,
  commerce_secure_cleanup_enabled: true,
  commerce_light_virtualization_enabled: true,
  commerce_secure_wallet_navigation_enabled: true,
  commerce_humanized_errors_enabled: true,
  enterprise_governance_enabled: true,
  enterprise_secure_channels_enabled: true,
  enterprise_controlled_onboarding_enabled: true,
  enterprise_security_governance_enabled: true,
  enterprise_archive_workflow_enabled: true,
  enterprise_internal_security_enabled: true,
};

const DEFAULTS: IndustrialFlagsState = IS_PRODUCTION ? PRODUCTION_DEFAULTS : DEV_SEED_ALIGNED_DEFAULTS;

const KNOWN_KEYS = new Set(Object.keys(DEFAULTS));

/** Keys declared for industrial shell defaults — used by drift tests vs `prisma/seed.ts` (Instruction 16A). */
export function getIndustrialFeatureFlagDefaultKeys(): string[] {
  return Object.keys(PRODUCTION_DEFAULTS);
}

export type IndustrialFeatureFlagsResult = {
  flags: IndustrialFlagsState;
  /** After first `/api/core/v1/feature-flags` attempt (Instruction 5A). */
  hydrated: boolean;
};

/**
 * Loads flags via same-origin proxy — avoids CORS to core-domain in dev.
 */
export function useIndustrialFeatureFlags(): IndustrialFeatureFlagsResult {
  const [flags, setFlags] = useState<IndustrialFlagsState>(DEFAULTS);
  const [hydrated, setHydrated] = useState(false);

  useEffect(() => {
    void fetch("/api/core/v1/feature-flags")
      .then((r) => (r.ok ? r.json() : null))
      .then((rows: { key: string; enabled: boolean }[] | null) => {
        if (!rows || !Array.isArray(rows)) return;
        if (!IS_PRODUCTION) {
          const keys = new Set(rows.map((r) => r.key));
          for (const k of KNOWN_KEYS) {
            if (!keys.has(k)) {
              console.warn(`[venext-flags] missing key from API: ${k} — using default`);
            }
          }
        }
        setFlags(() => {
          const next: IndustrialFlagsState = { ...DEFAULTS };
          for (const row of rows) {
            if (IS_PRODUCTION && !KNOWN_KEYS.has(row.key)) {
              next[row.key] = false;
            } else {
              next[row.key] = row.enabled;
            }
          }
          return next;
        });
      })
      .catch(() => {})
      .finally(() => setHydrated(true));
  }, []);

  return { flags, hydrated };
}
